### ISSUE TITLE
Importing Boost Releases, field report

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#524]
The scripts to import all the boost releases are amazing! Watching the large quantity of data be collected from the github api and go into the database.  Probably the scripts are mostly ready but there still could be a few issues. 

1. `./manage.py import_versions`

Many "message": "tag_not_found" . See note 1 below. Which tag is missing? Is this a concern?

After running `import_versions`, go to /releases/ page, select another version (let's say 1.75.0) in the drop-down, then it shows in the drop-down (Newest Version (1.75.0), which is wrong, because 1.75.0 is not the newest version.

2. `./manage.py update_libraries`

This crashes at hana in boost version 1.65.0. See note 2 below.

After it stops at this error, it doesn't proceed further.  All subsequent libraries are not imported, and don't appear on the website.

If the versions are processed sequentially, 1.82.0 1.81.0 1.80.0 , then only versions older than 1.65.0 would be missing.  However, after testing this in multiple environments, it appears that sometimes the version order is more random.  1.82.0, 1.80.0, 1.75.0 are missing.  1.81.0 and 1.79.0 are available. Why are some sets of libraries missing, and other sets of libraries shown on the webpage?  Presumably because it crashed on this hana bug, and didn't proceed further.  If I re-run `update_libraries` the error repeats, and the import won't finish.

3. `./manage.py update_libraries`

Doesn't accept --token as a parameter. Should be added?

Added the token as an environment variable.  

See Note 3 below. update_libraries consistently hits the "API rate limit exceeded for user ID 64418.." error.  This happens even when the github token has been set, and it's definitely using a real account rather than an anonymous account because it says user ID 64418..".  How critical is "API rate limit exceeded", and not being able to continue.  Next time will it pick up where it left off?  Perhaps the error always happens. Should the script notice when it gets the error "API rate limit exceeded", and purposely sleep 1 minute?  Is `update_libraries` non-critical data, such as number of pull requests, and it will be collected in the next cycle?  Maybe arrange the order of querying so if it's collecting "important" data first before any rate limit is reached. Or that is already how it works.  How about a summary at the end: what was imported, how much succeeded or failed, etc. (Although that might be a 
 less critical feature enhancement)

----------------------------------------------------------------

Note 1

```
./manage.py import_versions

root@boost-84c4688578-c4wrh:/code# ./manage.py import_versions
Skipping boost-1.83.0.beta1, not a full release
Saved version boost-1.82.0. Created: False
Skipping boost-1.82.0.beta1, not a full release
Saved version boost-1.81.0. Created: False
Skipping boost-1.81.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.80.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:08.487711Z"}
Saved version boost-1.80.0. Created: False
Skipping boost-1.80.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.79.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:09.593357Z"}
Saved version boost-1.79.0. Created: False
Skipping boost-1.79.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.78.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:10.753088Z"}
Saved version boost-1.78.0. Created: False
Skipping boost-1.78.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.77.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:11.878484Z"}
Saved version boost-1.77.0. Created: False
Skipping boost-1.77.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.76.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:12.953630Z"}
Saved version boost-1.76.0. Created: False
Skipping boost-1.76.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.75.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:14.052693Z"}
Saved version boost-1.75.0. Created: False
Skipping boost-1.75.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.74.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:15.146688Z"}
Saved version boost-1.74.0. Created: False
Skipping boost-1.74.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.73.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:16.232748Z"}
Saved version boost-1.73.0. Created: False
Skipping boost-1.73.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.72.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:17.330838Z"}
Saved version boost-1.72.0. Created: False
Skipping boost-1.72.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.71.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:18.467039Z"}
Saved version boost-1.71.0. Created: False
Skipping boost-1.71.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.70.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:19.650150Z"}
Saved version boost-1.70.0. Created: False
Skipping boost-1.70.0.beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.69.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:20.753298Z"}
Saved version boost-1.69.0. Created: False
Skipping boost-1.69.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.68.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:21.832811Z"}
Saved version boost-1.68.0. Created: False
{"message": "tag_not_found", "tag_name": "boost-1.67.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:22.947426Z"}
Saved version boost-1.67.0. Created: False
Skipping boost-1.67.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.66.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:24.056956Z"}
Saved version boost-1.66.0. Created: False
Skipping boost-1.66.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.65.1", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:25.183852Z"}
Saved version boost-1.65.1. Created: False
{"message": "tag_not_found", "tag_name": "boost-1.65.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:26.282873Z"}
Saved version boost-1.65.0. Created: False
Skipping boost-1.65.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.64.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:27.380473Z"}
Saved version boost-1.64.0. Created: False
Skipping boost-1.64.0-beta2, not a full release
Skipping boost-1.64.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.63.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:28.461649Z"}
Saved version boost-1.63.0. Created: False
Skipping boost-1.63.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.62.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:29.549966Z"}
Saved version boost-1.62.0. Created: False
Skipping boost-1.62.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.61.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:30.715106Z"}
Saved version boost-1.61.0. Created: False
Skipping boost-1.61.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.60.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:31.869780Z"}
Saved version boost-1.60.0. Created: False
Skipping boost-1.60.0-beta1, not a full release
{"message": "tag_not_found", "tag_name": "boost-1.59.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:32.966832Z"}
Saved version boost-1.59.0. Created: False
{"message": "tag_not_found", "tag_name": "boost-1.58.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:34.079566Z"}
Saved version boost-1.58.0. Created: False
{"message": "tag_not_found", "tag_name": "boost-1.57.0", "repo_slug": "boost", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T16:21:34.592622Z"}
Saved version boost-1.57.0. Created: False
Skipping boost-1.57.0-beta1, not a full release

```

Note 2

```
Saved library version DLL (boost-1.65.0). Created? False
Processing module compute...
{"message": "library_udpated", "library": {"name": "Compute", "key": "compute", "authors": ["Kyle Lutz"], "description": "Parallel/GPU-computing library", "category": ["Concurrent"], "maintainers": ["Kyle Lutz <kyle.r.lutz -at- gmail.com>"], "cxxstd": null, "last_github_update": "2023-07-12T12:08:28+00:00", "github_url": "https://github.com/boostorg/compute"}, "obj_created": false, "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T00:41:55.319998Z"}
Saved library version Compute (boost-1.65.0). Created? False
Processing module libs/hana...
{"message": "get_library_metadata_failed", "repo": "libs/hana", "url": "https://raw.githubusercontent.com/boostorg/libs/hana/master/meta/libraries.json", "logger": "libraries.github", "level": "error", "timestamp": "2023-07-14T00:41:55.476295Z", "exception": "Traceback (most recent call last):\n  File \"/code/libraries/github.py\", line 223, in get_libraries_json\n    response.raise_for_status()\n  File \"/venv/lib/python3.11/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/boostorg/libs/hana/master/meta/libraries.json"}
Traceback (most recent call last):
  File "/code/./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.11/site-packages/djclick/adapter.py", line 68, in run_from_argv
    exit_code = self.main(
                ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/djclick/adapter.py", line 50, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/libraries/management/commands/import_library_versions.py", line 61, in command
    github_data = client.get_repo(repo_slug=library_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/libraries/github.py", line 284, in get_repo
    return self.api.repos.get(owner=self.owner, repo=repo_slug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ghapi/core.py", line 62, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ghapi/core.py", line 121, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/fastcore/net.py", line 218, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/fastcore/net.py", line 119, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcore.net.HTTP404NotFoundError: HTTP Error 404: Not Found
====Error Body====
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

```

Note 3

```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nfastcore.net.HTTP403ForbiddenError: HTTP Error 403: Forbidden\n====Error Body====\n{\n  \"message\": \"API rate limit exceeded for user ID 64418644.\",\n  \"documentation_url\": \"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"\n}\n"}
{"message": "library_udpated", "library": {"name": "Compat", "key": "compat", "authors": ["Peter Dimov"], "description": "C++11 implementations of standard components added in later C++ standards.", "category": ["Emulation", "Programming"], "maintainers": ["Peter Dimov <pdimov -at- gmail.com>"], "cxxstd": "11", "last_github_update": "2023-05-16T22:35:39+00:00", "github_url": "https://github.com/boostorg/compat"}, "obj_created": false, "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T15:00:51.403828Z"}
{"message": "updating_monthly_commit_data", "logger": "libraries.github", "level": "info", "timestamp": "2023-07-14T15:00:51.442233Z"}
{"message": "get_all_commits_failed", "repo": "compat", "exc_msg": "HTTP Error 403: Forbidden\n====Error Body====\n{\n  \"message\": \"API rate limit exceeded for user ID 64418644.\",\n  \"documentation_url\": \"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"\n}\n", "logger": "libraries.github", "level": "error", "timestamp": "2023-07-14T15:00:51.611700Z", "exception": "Traceback (most recent call last):\n  File \"/code/libraries/github.py\", line 117, in get_commits\n    pages = list(\n            ^^^^^\n  File \"/venv/lib/python3.11/site-packages/ghapi/page.py\", line 16, in paged\n    yield from itertools.takewhile(noop, (oper(*args, per_page=per_page, page=i, **kwargs) for i in range(1,max_pages+1)))\n  File \"/venv/lib/python3.11/site-packages/ghapi/page.py\", line 16, in <genexpr>\n    yield from itertools.takewhile(noop, (oper(*args, per_page=per_page, page=i, **kwargs) for i in range(1,max_pages+1)))\n                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/ghapi/core.py\", line 62, in __call__\n    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/ghapi/core.py\", line 121, in __call__\n    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/fastcore/net.py\", line 218, in urlsend\n    return urlread(req, return_json=return_json, return_headers=return_headers)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/fastcore/net.py\", line 119, in urlread\n    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nfastcore.net.HTTP403ForbiddenError: HTTP Error 403: Forbidden\n====Error Body====\n{\n  \"message\": \"API rate limit exceeded for user ID 64418644.\",\n  \"documentation_url\": \"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"\n}\n"}
{"message": "get_first_tag_and_date_failed", "repo": "compat", "logger": "libraries.github", "level": "error", "timestamp": "2023-07-14T15:00:51.786544Z", "exception": "Traceback (most recent call last):\n  File \"/code/libraries/github.py\", line 157, in get_first_tag\n    tags = self.api.repos.list_tags(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/ghapi/core.py\", line 62, in __call__\n    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/ghapi/core.py\", line 121, in __call__\n    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/fastcore/net.py\", line 218, in urlsend\n    return urlread(req, return_json=return_json, return_headers=return_headers)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/fastcore/net.py\", line 119, in urlread\n    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nfastcore.net.HTTP403ForbiddenError: HTTP Error 403: Forbidden\n====Error Body====\n{\n  \"message\": \"API rate limit exceeded for user ID 64418644.\",\n  \"documentation_url\": \"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"\n}\n"}

```

**Comment by williln** [comment]
Hi @sdarwin -- I'll be creating some issues that branch off of this one to address some of the bugs you raised. 

---

> Many "message": "tag_not_found" . See note 1 below. Which tag is missing? Is this a concern? 

This is a quirk of how GitHub distinguishes between a "tag" and a "release." We get a list of all the tags for the Boost repo from the `list_tags` endpoint. Some of those tags are full releases, and others are just tags. 

Once we get all the tags for the Boost repo, we loop through them. We skip the `beta` and `rc` releases, and anything in version `0.*`. Then, we call the `get_release_by_tag` endpoint for the GitHub API for each tag to gets its metadata (namely, the release date). But not all Boost tags are also full releases. In this case, we call the `get_commit` endpoint with the commit SHA of the tag to get this information. We could call `get_commit` in every case, but the data in `get_release_by_tag` is more accurate, particularly for the release date.  

When we don't find the release in `get_release_by_tag`, we log the error (which is what you may see in the output), but we follow up by getting the data from the commit endpoint.

**Comment by sdarwin** [comment]
It looks like the github api rate limit is per hour, not per minute or second.  So sleeping 1 minute wouldn't have any effect.   So, maybe the script could detect when it hits the api limit, by parsing the returned value, and seeing the code or message "API rate limit exceeded".    Based on that, it would stop, and wait until the next time around.    Pick up where it left off.

**Comment by williln** [comment]
> After running import_versions, go to /releases/ page, select another version (let's say 1.75.0) in the drop-down, then it shows in the drop-down (Newest Version (1.75.0), which is wrong, because 1.75.0 is not the newest version.

Addressed in https://github.com/cppalliance/temp-site/pull/539

**Comment by sdarwin** [comment]
1. At the moment if I run this command:

```
./manage.py import_library_versions		
```

It imports 1.83, 1.82, 1.81, and then stops without showing a reason. Should it continue to all versions?

2. For this command:

```
./manage.py import_library_version_docs_urls
```

is the path to documentation consistent enough that an external script would not be needed:  
```
libs/libraryname
```

or the script is only to process a few exceptions? 

maybe docs/command.md could include a few examples.  

Library: beast , docs url: __  , Library: json , docs url:  __ 

3. 

```
./manage.py update_libraries
```

When this runs, it shows outputs such as:  

`{"message": "commit_data_updated", "commit_data_pk": 183, "obj_created": true, "library": "Multi-Array", "branch": "master", "logger": "libraries.github", "level": "info", "timestamp": "2023-08-17T22:53:25.748497Z"`

I'm wondering, did that just query "Multi-Array" about Issues in June 2020, or number of Pull requests in August 2021, or number of Commits?  Could the output messages display what it discovered?   how many commits or issues did it find? which month?
