### ISSUE TITLE
Bug: Celery error in `update_libraries` 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#889]
Fixing #881 seems to have exposed another bug! 

```
celery-worker_1  | Arguments: {'hostname': 'celery@45078e69dac7', 'id': '1a8a8522-e6de-4911-abd0-7c283058011b', 'name': 'libraries.tasks.update_libraries', 'exc': 'TypeError("LibraryUpdater.update_libraries() got an unexpected keyword argument \'since\'")', 'traceback': 'Traceback (most recent call last):\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/code/libraries/tasks.py", line 83, in update_libraries\n    updater.update_libraries(since=since, until=until)\nTypeError: LibraryUpdater.update_libraries() got an unexpected keyword argument \'since\'\n', 'args': '[]', 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
```

I'll fix it.

**Comment by williln** [comment]
Could not reproduce once I pulled from `develop`. Successfully ran the update task. Closing for now but can reopen if it reappears.
